name = "Whitespaces"
uuid = "515c8ec7-7941-45b7-a96a-b6024ada3348"
authors = ["goropikari <goropikari56@gmail.com>"]
version = "0.1.0"

[deps]
Automa = "67c07d97-cdcb-5c2c-af73-a7f9c32a568b"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
